"""gasto_fixo + transacao.gasto_fixo_id

Revision ID: 91501cf113ee
Revises: f6c1a9bc8d20
Create Date: 2026-06-10 20:11:38.528727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Reaproveita o tipo enum 'payment_method' já existente (criado na migration
# inicial). create_type=False impede o CREATE TYPE duplicado.
_payment_method = postgresql.ENUM(
    "pix", "card", "cash", "transfer", name="payment_method", create_type=False
)


# revision identifiers, used by Alembic.
revision: str = '91501cf113ee'
down_revision: Union[str, None] = 'f6c1a9bc8d20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gasto_fixo',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('expected_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('default_account_id', sa.Integer(), nullable=True),
    sa.Column('default_payment_method', _payment_method, nullable=True),
    sa.Column('due_day', sa.Integer(), nullable=True),
    sa.Column('start_year', sa.Integer(), nullable=False),
    sa.Column('start_month', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['default_account_id'], ['conta.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('transacao', sa.Column('gasto_fixo_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        'fk_transacao_gasto_fixo_id', 'transacao', 'gasto_fixo', ['gasto_fixo_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_constraint('fk_transacao_gasto_fixo_id', 'transacao', type_='foreignkey')
    op.drop_column('transacao', 'gasto_fixo_id')
    op.drop_table('gasto_fixo')
